### ISSUE TITLE
How do we tie the services together?

### ISSUE THREAD

**Issue by timberhill** [flam-flam/flam-flam.github.io#11]
We need to choose how to manage services in multiple repositories. Within the Phase 1 work, it only needs to work in a docker-compose. In the next phase, however, we will need to package them all in a helm chart and run that in a local KIND cluster, for instance.

## Option 1 - dedicated repo

Keep the `docker-compose.yaml` in a separate repo (e.g. `dev`, `glue`, `infrastructure` etc). In Phase 2 we could keep the KIND cluster config here as well.

➕ services get to stay completely independent

➖ docker-compose is maintained separately to everything and will have to include relative paths

## Option 2 - docker-compose in each service repo

Maintain a `docker-compose.yaml` in each repo. The service in the repo is built from the repo docker-compose is in, while other services' latest image will be pulled from `ghcr.io`.

➕ no separate repo, docker-compose can be run in the same repo as the service code, making it easier to develop the service itself

➖ changes to the setup will need to be replicated across all repositories, including the database the services are talking to

## Option 3 - ???

**Comment by timberhill** [comment]
I am personally leaning to the second option suggested by @chipe88, as the docker-compose files should not get too many changes in Phase 1 and Phase 2 should rely more on kubernetes and helm charts

**Comment by danyloid** [comment]
Since this is a temporary solution, until we start using k8s & helm - does not really matter, I am fine with both.

**Comment by timberhill** [comment]
as we plan to deploy this with helm soon anyway, might as well set up a `helm-charts` repo [with github pages](https://helm.sh/docs/topics/chart_repository/#github-pages-example) so that helm could pull the versioned charts directly from the repo.

This is what it would look like more or less: https://github.com/two-tauers/helm-charts

The only addition will be the e.g. `infrastructure` folder at the root that can contain a docker-compose file and maybe also the KIND config.

@danyloid @chipe88 sounds good?

**Comment by timberhill** [comment]
https://github.com/flam-flam/helm-charts
