### ISSUE TITLE
Document the services on the website

### ISSUE THREAD

**Issue by timberhill** [flam-flam/flam-flam.github.io#14]

**Comment by fratcliffe** [comment]
@timberhill might we be able collaborate on some ACs for this? I've been blocking myself all day because I can't decide what format it should take 😅

**Comment by timberhill** [comment]
Haha yes. I am not sure myself, but was imagining something fairly brief? e.g.:

- Git repo link
- Language it's written in
- Description of the functionality, which is quite small right now of course, they don't do much
- Published images
- Usage - docker things
- Endpoints
- Config

If it's possible to have some badges with the latest tag of the image/repo lime in the dispatcher readme, that would be quite nice too.

**Comment by fratcliffe** [comment]
Ahh yess! See this is exactly what I needed, it's bonkers how someone saying largely the same words in a different order to how you had them in your head with a few supplemental words thrown in can really shake things up 😀 thank you!

**Comment by fratcliffe** [comment]
testing webhook in gh admin channel...
